### ISSUE TITLE
How does it work?? No more data-sr attributes?!

### ISSUE THREAD

**Issue by HybridSolutions** [jlmakes/scrollreveal#329] opened 2017-02-25 04:06 UTC
Hi,

I was working with version 2 and after checking the plugin updates, I got completly lost. How does the current version work? Only using code? No more CSS attributes?

**Comment by jlmakes** [comment] 2017-02-25 08:55
Hi @HybridSolutions,

ScrollReveal 2 uses HTML `data-sr` attributes to define animation characteristics.
ScrollReveal 3 uses JavaScript `reveal()` calls to define animation characteristics.

**The primary reasons for this change:**

* Just like inline CSS vs. stylesheets, it's simpler (and cleaner) to maintain a single source of truth than every occurrence throughout your project.
* The `data-sr` attribute had some warts:
    * Doesn’t support element specific callbacks
    * Doesn’t support all available options (e.g. custom containers, disabling mobile, delay type)
    * Easing required a `move` keyword replacement, even if your animation didn't.
* Version 2 failed to provide the flexibility often expected of a modern JavaScript library, like working with asynchronous content, other JavaScript and various feature requests.

### Basic Migration Example

_Version 2:_

```js
window.sr = new scrollReveal()
```
```html
<div data-sr="enter bottom and move 20px over 2s"></div>
```

_Version 3:_

```html
<div id="example"></div>
```
```js
window.sr = new ScrollReveal()

sr.reveal('#example', {
    origin: 'bottom',
    distance: '20px',
    duration: 2000,
})
```

The [v3 documentation](https://github.com/jlmakes/scrollreveal#1-getting-started) should walk you through everything you need to know to get version 3 working if you're ready to get started.

However, it's worth mentioning that [v4 is in public beta](https://github.com/jlmakes/scrollreveal/pull/323), and a new website with brand new documentation is currently in development. I've written your username down, and will mention you on GitHub when it releases.

Version 4 is 99% backwards compatible with version 3, and mostly a new test suite, bug fixes and some feature improvements... so it's up to you: you can get started with modern ScrollReveal today and check out the [v3 documentation](https://github.com/jlmakes/scrollreveal#1-getting-started), or wait a couple weeks and dive right into version 4 and the new documentation.

***

Duplicate of #194 #205 #207 #224

**Closed** 2017-02-25 09:04 UTC
Labels: Duplicate, Legacy, Question
