### ISSUE TITLE
transition:none in Chrome/Safari

### ISSUE THREAD

**Issue by Metis77** [jlmakes/scrollreveal#231] opened 2016-02-10 21:27 UTC
While firefox and IE work, in Chrome and Safari `transition:none` is set.

``` css
transition: none 0s ease 0s, transform 0.8s cubic-bezier( 0.6, 0.2, 0.1, 1 ) 0s, opacity 0.8s cubic-bezier( 0.6, 0.2, 0.1, 1 ) 0s;
```

The js should be fine (?):

``` js
    /**
     * private functions
     */
    var elements = ('.ce_vimeo_album, .ce_text, .ce_epf_layout');
    var config  = {
        viewFactor : 0.15,
        duration   : 800,
        distance   : "100px",
        delayType  : "onload",
        scale      : 0.8,
        reset       : false, 
        viewOffset  : { top: 20 }
    };


    /**
     * public functions
     */
    var self = {};

    self.init = function(){

        window.sr    = ScrollReveal();
        sr.reveal( elements, config );

        console.log('ScrollReveal');
    };


     /**
     * do stuff
     */


    self.init();
```

**Comment by Metis77** [comment] 2016-02-10 21:59
Seams like the script ran too early (on document.ready).
Needed to wait for window.load, while it is at the very bottom of the document.
Is this a bug?

**Comment by allaire** [comment] 2020-03-11 01:57
@jlmakes Sorry for bringing this up from the death, but I just experienced this weird issue. My `vendor.js` file is just before the closing `</body>`.

When I have:

```js
import { throttle } from "lodash";
import ScrollReveal from "scrollreveal";

// Reveals on scroll

const sr = ScrollReveal();

sr.reveal(".js-features__image-wrapper-left", {
  delay: 5000,
  easing: "ease-in"
});
```
I get the following:

`<div class="features__image-wrapper js-sr js-features__image-wrapper-left" data-sr-id="0" style="visibility: visible; opacity: 1; transition: none 0s ease 0s, opacity 0.6s ease-in 5s;">` with `transition: none;`

The only way I can make this work correctly is by wrapping it onload:

```js
import { throttle } from "lodash";
import ScrollReveal from "scrollreveal";

// Reveals on scroll

window.addEventListener("load", () => {
  const sr = ScrollReveal();

  sr.reveal(".js-features__image-wrapper-left", {
    easing: "ease-in"
  });
});
```

Since everything is at the bottom of the file, I didn't expect to have it wrapped onload. Can you shed some light on that behaviour?

Thanks!

**Comment by jlmakes** [comment] 2020-03-15 06:56
The default transition property varies across browsers. According to the tests I ran, there were 4 possible values. See my annotations in the source:

https://github.com/jlmakes/scrollreveal/blob/66f44ab08c3cd0a3df7ced9b2e01e4ffcf809cb2/src/instance/functions/style.js#L173-L182

I don't recall what browser each value corresponds to, but a cursory check suggests that WebKit based browsers (such as Chrome and Safari) use `all 0s ease 0s` as the default.

Why that value would be `none 0s ease 0s` in any of the tested browsers is beyond me. Let alone why it would depend upon the page load event, and _not_ be reproducible.

That said, it would seem there's reason to include that case in the regex, e.g:

```diff
- !transition.computed.match(/all 0s/)
+ !transition.computed.match(/all 0s|none 0s/)
```

Is that something you can test @allaire ?

**Comment by jlmakes** [comment] 2020-03-15 06:57
The default transition property varies across browsers. According to the tests I ran, there were 4 possible values. See my comments in the source:

https://github.com/jlmakes/scrollreveal/blob/66f44ab08c3cd0a3df7ced9b2e01e4ffcf809cb2/src/instance/functions/style.js#L173-L182

I don't recall what browser each value corresponds to, but a cursory check suggests that WebKit based browsers (such as Chrome and Safari) use `all 0s ease 0s` as the default.

Why that value would be `none 0s ease 0s` in any of the tested browsers is beyond me. Let alone why it would depend upon the page load event, and/or _not_ be reproducible.

That said, it would seem there's reason to include that case in the regex, e.g:

```diff
- !transition.computed.match(/all 0s/)
+ !transition.computed.match(/all 0s|none 0s/)
```

Is that something you can test @allaire ?

**Comment by allaire** [comment] 2020-03-15 12:26
Hi @jlmakes, your fix does work! Now everything works as expected. 

The only difference versus using `onload`` is that there is no reveal animation when you are already scrolled to an element that is `.reveal()`, which is expected since the code runs right away.

Found some resources on Google about `transition: none 0s`:

https://chromium.googlesource.com/chromium/src/+/master/third_party/blink/web_tests/transitions/transitions-parsing-005.html#37

https://github.com/75lb/transition-to-from-auto/issues/5

**Comment by jlmakes** [comment] 2020-03-16 04:23
Cool links, thanks. The Chromium source is especially interesting! This suggests that somehow `window.onload` impacts whether the transition default value is an empty string, or "none".

Weird :D

**Closed** 2020-03-16 04:42 UTC
Labels: Bug, Needs Demo

**Comment by allaire** [comment] 2020-03-16 13:09
Awesome @jlmakes, thanks for the great work and support. 🍻
