### ISSUE TITLE
Async doesn't reveal properly when added to already visible area of viewport

### ISSUE THREAD

**Issue by treechime** [jlmakes/scrollreveal#397] opened 2017-11-23 04:59 UTC
I have a grid of content with a button to load more via ajax. After the content has been loaded, I call ```sync()``` which works in attaching handlers, but does not reveal the items if they are being added to the already visible area of the viewport.

They only seem to be triggered as visible once the top of the element reaches the top of the viewport. After this they work fine.

Also only seems to be an issue when using sequences. I'm assuming it's something to do with being added midway through a sequence, therefore not being triggered by the first element in the sequence which has already passed...?

Here's a stripped down version of what I'm experiencing: [https://jsfiddle.net/q3wa5co8/5/](https://jsfiddle.net/q3wa5co8/5/)

So close to working perfectly!

* Windows 10
* Chrome 62.0.3202.94 (64-bit)
* Firefox 56.0.2 (32-bit)
* Microsoft Edge 40.15063.674.0
* ScrollReveal 4.0.0-beta.23

**Comment by jlmakes** [comment] 2017-11-23 19:16
Thanks for fiddle, Morgan. I’ll look into this over the weekend.

**Comment by jlmakes** [comment] 2018-01-22 05:55
This isn't fixed yet, but I now understand the problem. Here's the state before and after `sync()`

![dump](https://user-images.githubusercontent.com/2044842/35206089-66824c98-ff3a-11e7-893a-c4cad2c02410.png)

What stands out to me is that the `Sequence` object is being re-initialized on `sync()`, but [the oversight](https://github.com/jlmakes/scrollreveal/blob/development/src/instance/functions/sequence.js#L23) is that ScrollReveal expects freshly initialized sequences to have an empty `revealed<SequenceModel>` to begin sequencing elements.

Otherwise `headblocked` and `footblocked` stay `true` (their initial value, blocking both upward and downward sequences) and nothing happens _until you scroll all revealed elements out of view_, emptying `revealed<SequenceModel>` and satisfying the expected initial condition.

> There is actually [another unreliable assumption](https://github.com/jlmakes/scrollreveal/blob/development/src/instance/functions/sequence.js#L136) in the source, expecting sequenced elements to reveal in source order (as opposed to the order they appear in the DOM).

Thanks again for using ScrollReveal, and taking the time to help improve it. I'm going to work on the sequencer, and cut a new release this week.

**Comment by treechime** [comment] 2018-01-22 05:59
Glad to hear, thanks for looking into it!

**Comment by jlmakes** [comment] 2018-02-07 14:10
Landed in `v4.0.0-beta.26` along with some other improvements to the sequencer.

Thanks again for helping make ScrollReveal better @treechime!

**Comment by jlmakes** [comment] 2018-02-07 17:06
I noticed that with `options.reset = false` the entire sequence re-reveals, which I initially thought was a regression—but I realize now your original example used `reset: true`.

The reason is that `clean()` is called internally after the `afterReveal` callback, to remove unneeded styles and event listeners from elements. I'm considering removing this behavior for sequenced elements, so your original example works as expected with or without the `reset` option.

For now, `beta.26` solves your original problem: https://jsfiddle.net/q3wa5co8/6/

**Closed by jlmakes** 2018-02-07 17:06 UTC
Labels: Bug
