### ISSUE TITLE
Demo not working in Internet Explorer (Invalid CSS)

### ISSUE THREAD

**Issue by vladox** [jlmakes/scrollreveal#222] opened 2016-01-18 20:41 UTC
Hi 
By visiting https://scrollrevealjs.org/ o IE10+ (i.e. 10 and 11) I get a black screen. I have JS enabled.
I don't see any js errors in the console. And i've tried in 2 different machines. It's there something I'm missing? 
Regards
Vlad

**Comment by jlmakes** [comment] 2016-01-19 05:42
Thanks for the heads up @vladox :bow: 

I believe this isn’t actually an issue with ScrollReveal, but with the JavaScript on the demo site. I was sniffing the User Agent incorrectly, but no matter, it should be fixed now.

Please confirm!

**Comment by jlmakes** [comment] 2016-01-19 06:18
What’s strange is that the reveals on the header region work fine, it’s the bars that are failing. I’m looking into this, thanks @vladox :bow:

**Comment by vladox** [comment] 2016-01-20 00:54
@jlmakes Thanks for your feedback. I hope you find that pesky bug :pray:

**Comment by jlmakes** [comment] 2016-01-20 06:17
@vladox I can confirm ScrollReveal works fine in Internet Explorer 10+, but you’re correct—there is something wrong with the demo in Internet Explorer.

I’ve discovered that my use of the newer CSS values `vw` and `vh` (perhaps in addition to `display: flex`) do not play nice with Internet Explorer, even though there is allegedly [fair support](http://caniuse.com/#search=vw) — this is why the introduction works fine, because it does not use those units.

Thanks again for the heads up @vladox, I will revise the demo to use different CSS.

**Closed** 2017-12-17 18:36 UTC
Labels: Browser, Bug
