### ISSUE TITLE
ScrollReveal v4 beta sequencer breaks if you scroll too fast

### ISSUE THREAD

**Issue by AbrahamHalil** [jlmakes/scrollreveal#341] opened 2017-04-25 09:07 UTC
Hi,

if i scroll fast to the bottom ScrollReveal doesn't work because Scroll Reveal is waiting for the previous reveal to finish. Is there a way to fix this problem.

Thanks!

**Comment by geosenna** [comment] 2017-04-25 10:27
+1

**Comment by jlmakes** [comment] 2017-04-25 14:31
You asked about using sequences in #339, which reveals elements one after another.

If you no longer want elements at the bottom to wait for previous reveals, the simple answer is to not use the sequencer (by removing the interval from your reveal call).

```js
//                            sequence interval
//                                    |
sr.reveal('.box', { duration: 2000 }, 50)

// instead, use a regular reveal...
sr.reveal('.box', { duration: 2000 })
```

**Comment by jlmakes** [comment] 2017-04-27 17:11
I misunderstood this issue @AbrahamHalil...

Here is a [SRv4 Sequencer Demo](http://jsbin.com/kajohaf/3/edit?html,output), and the bug is easily reproduced—simply scroll faster than the sequence, and it is interrupted. To continue the sequence, one must scroll back to the last revealed element in the sequence.

I’ll have to work through the desired behavior again. The behavior you observed in SRv3 (#339) has come up time and time again as undesired—but once again, progressively revealed sequences prove complicated to get right.

**Comment by jlmakes** [comment] 2017-04-27 17:13
I misunderstood this issue @AbrahamHalil...

Here is a [SRv4 Sequencer Demo](http://jsbin.com/kajohaf/3/edit?html,output), and the bug is easily reproduced—simply scroll faster than the sequence, and it is interrupted. To continue the sequence, one must scroll back to the last revealed element in the sequence.

Looks like I’ll have to work through the desired behavior again. The behavior you observed in SRv3 (#339) has come up time and time again as undesired—but once again, progressively revealed sequences prove complicated to get right.

**Comment by jlmakes** [comment] 2017-05-16 02:25
🎉 @AbrahamHalil @geosenna

Thanks for bringing this to my attention—it was a great brain teaser, and actually really helped keep me motivated! (I was sort of stuck doing CSS and technical writing for the documentation before you brought this up)

**This is now fixed in v4.0.0-beta.5**

### Please have fun (and try to break it) here → [SRv4 Sequencer Demo Fixed](http://jsbin.com/nugatod/1/edit?html,css,output)

**Closed by jlmakes** 2017-05-16 02:25 UTC
Labels: Beta, Bug

**Comment by grahammcuk** [comment] 2017-05-18 13:24
Works perfectly for me 👍

**Comment by AbrahamHalil** [comment] 2017-05-18 13:28
It is really great. I tested also the others, ScrollReveal ist the best scroll animation plugin ever.

**Comment by Mohsen-Khakbiz** [comment] 2017-05-31 10:34
it's working pretty good now. but still have to wait for elements those are not in viewport.
checked the latest demo here http://jsbin.com/totumop/2/edit?html,css,output
have a fast scroll to the bottom and see the items have some delay until they fade in.
maybe we can ignore those elements are not in viewport and only fade in the items are in viewport?

sorry for my bad English and thanks for such a great plugin

**Comment by AbrahamHalil** [comment] 2017-06-01 12:56
Hi,

as i see it works well on Safari(MacOS). Some animations doesn`t work on Chrome or on Firefox.

I added this code below to the jsbin-demo.  Please try it safari, chrome and firefox to see the difference.

http://jsbin.com/jatesufafe/edit?html,output

```
<script>
		sr.reveal('.blocks li', {
			// 'bottom', 'left', 'top', 'right'
				origin: 'bottom',

				// Can be any valid CSS distance, e.g. '5rem', '10%', '20vw', etc.
				distance: '0px',

				// Time in milliseconds.
				duration: 800,
				delay:200,

				// Starting angles in degrees, will transition from these values to 0 in all axes.
				rotate: { x: 0, y: 0, z: 0 },

				// Starting opacity value, before transitioning to the computed opacity.
				opacity: 0,

				// Starting scale value, will transition from this value to 1
				scale: 0,

				// Accepts any valid CSS easing, e.g. 'ease', 'ease-in-out', 'linear', etc.
				/* easing: 'cubic-bezier(0.6, 0.2, 0.1, 1)', */
				easing: 'ease',

				// `<html>` is the default reveal container. You can pass either:
				// DOM Node, e.g. document.querySelector('.fooContainer')
				// Selector, e.g. '.fooContainer'
				container: window.document.documentElement,

				// true/false to control reveal animations on mobile.
				mobile: true,

				// true:  reveals occur every time elements become visible
				// false: reveals occur once as elements become visible
				reset: true,

				// 'always' — delay for all reveal animations
				// 'once'   — delay only the first time reveals occur
				// 'onload' - delay only for animations triggered by first load
				useDelay: 'always',

				// Change when an element is considered in the viewport. The default value
				// of 0.20 means 20% of an element must be visible for its reveal to occur.
				viewFactor: 0.2,

				// Pixel values that alter the container boundaries.
				// e.g. Set `{ top: 48 }`, if you have a 48px tall fixed toolbar.
				// --
				// Visual Aid: https://scrollrevealjs.org/assets/viewoffset.png
				viewOffset: { top: 48, right: 0, bottom: 0, left: 0 },


		}, 60)
	</script>
```

**Comment by AbrahamHalil** [comment] 2017-06-01 13:11
Ok, i think i find the Reason for the difference Results on different browsers. 

If i set **"scale: 0,"**.  it works only on Safari(MasOS). Scale effect doesn't work on Chrome or on Firefox. **"Scale"** must be greater then 0. It works with **"scale: 0.1"**

**Comment by jlmakes** [comment] 2017-06-01 18:25
@Mohsen-Khakbiz For a few reasons, I don't think this is plausible.

If you’re concerned about this, I would recommend not using sequences.

```js
// instead of passing an interval
// which creates a sequenced reveal
sr.reveal(selector, options, interval)

// create normal reveals
sr.reveal(selector, options)
```

**Comment by jlmakes** [comment] 2017-08-10 02:46
I’ve spent a few weeks continuously trying to improve the sequencer, and I think I’ve finally built the best one yet. Unless you guys can break it, I think the beta is almost over.

Check it out in `v4.0.0-beta.10` — @AbrahamHalil @geosenna @grahammcuk @Mohsen-Khakbiz

`npm i scrollreveal@beta` or `https://unpkg.com/scrollreveal@beta`
