### ISSUE TITLE
Jest - Testing react component with scrollreveal uses

### ISSUE THREAD

**Issue by renatobenks** [jlmakes/scrollreveal#343] opened 2017-05-06 04:58 UTC
Jest - Testing react component with scrollreveal uses
--

Issue reference #218 

- Ubuntu 16.4/64 bits
- Google Chrome 58.0.3029.96 (64-bit)
- Version: 3.3.5

Hey @jlmakes and everyone, any idea in how cover with unit tests the scrollreveal uses in component react with [Jest](https://facebook.github.io/jest/) with environment Node, and `react-test-renderer` lib to shoot snapshots? (Not using enzyme or other lib within).

I'm using document, window, etc, mocked to test scrollreveal behaviour, what already cost me too much hard works and time.

Here is my component to test
```javascript
class ScrollAnimate extends Component {
    static getOffset ({top, left, right, bottom}) {
        return {
            top: top || 0,
            left: left || 0,
            right: right || 0,
            bottom: bottom || 0
        }
    }

    constructor (props) {
        super(props);
        this.state = {
            scroll: new ScrollReveal({
                scale: !!props.scale ? props.scale === true ? 0.1 : props.scale : null,
                duration: props.duration || 1500,
                reset: !!props.reset,
                viewFactor: props.view || 0.2,
                viewOffset: props.offset
                    ? ScrollAnimate.getOffset(props.offset)
                    : ScrollAnimate.getOffset({})
            }, 50)
        }
    }

    componentDidMount () {
        const { scroll } = this.state;
        const { loadAfter, children } = this.props;
        scroll.reveal(String.prototype.concat('#', children.props.id), {
            afterReveal () {
                return loadAfter();
            }
        });
    }

    render () {
        return this.props.children;
    }
}
```

I can resolve some issues fixing my mocks of global variables, like `window, document, etc`. So, this way, I believe that my issues is about my global variables no mocking correctly for ScrollReveal to work.

Really my issue is:
- on `componentDidMount`, the `afterReveal` method from ScrollReveal is not being called.

**Comment by jlmakes** [comment] 2017-05-06 14:49
Unit testing the DOM and its behavior with ScrollReveal (without React) is something I'm still figuring out. I can't strongly recommend a specific practice, but I can help explain more of what's happening under the hood of ScrollReveal.

Maybe something in these details will help you create a satisfactory unit test.


<details>

***

### ⚠️ Disclaimer
Let’s be clear that this is for version 3.x of ScrollReveal. The data structures and behavior of the version 4 beta is NOT the same in all cases.

***

_When we instantiate..._
```js
var sr = new ScrollReveal();
```
- If ScrollReveal is not supported, the constructor will attempt to `console.log` an error message.

- If ScrollReveal IS supported, then...
1. The `sr.history` array will have length `0`
2. The `sr.initialized` property will be `false`
3. The `sr.store.elements` object will be empty.

***

_When we create our first reveal..._
```html
<div class="someClass"></div>
<div class="someClass"></div>
```
```js
sr.reveal('.someClass');
```
- If the `.someClass` selector returned 0 elements, nothing would happen/change.

- But since 2 elements are returned here...
1. The `sr.history` array will have a length of `1`
2. The `sr.initialized` property will be `true`
3. The `sr.store.elements` object will contain 2 objects.

Also, there will be some DOM changes:
```html
<div class="someClass" data-sr-id="1" style="..."></div>
<div class="someClass" data-sr-id="2" style="..."></div>
```
The `data-sr-id` has been added to all elements returned by the `.someClass` selector. The id assigned to this attribute corresponds to the `sr.store.elements` keys. So for example...

```js
sr.store.elements[2]
```

Would return all the data for:
```html
<div class="someClass" data-sr-id="2" style="..."></div>
```

Like this:
```js
{
    config: Object
    domEl: div
    id: 2
    revealing: Boolean
    seen: Boolean
    styles: Object
    timer: null
}
```
</details>

**Comment by renatobenks** [comment] 2017-05-06 17:59
All right, thansk for response.

So @jlmakes, with my case to test I made a search whats happening and debugging inside him I could know a little more about scrollreveal feature and so, I'm fine about scrollreveal features.

So, about make ref's to DOM on components, following React instructions this is a bad practice, in this case, I couldn't pass my DOM element to scrollreveal, I just works with string to scrollreveal resolves and get the DOM.

I can resolve some issues fixing my mocks of global variables, like `window, document, etc`.

So, this way, I believe that my issues is about my global variables no mocking correctly to scrollreveal works fine.

My really issue is:
- `afterReveal` defined on `componentDidMount` from scrollreveal it's not calling.

**Comment by jlmakes** [comment] 2017-05-06 20:38
The callbacks rely on both `window.cancelTimeout` and `window.setTimeout`. If you’ve mocked the `window` object, perhaps the issue that it does not have these methods?

**Comment by renatobenks** [comment] 2017-05-07 20:25
I've mocked `setTimeout` and `clearTimeout`, I'm calling callback instantly on timeout, just calling calback, (`setTimeout: (callback, time) => callback()`), because, mocking timeout with native timeout from node causes inifite looping, timeout calling each other, and this way, apparently should be works, and seems to me it's working, like before with just timeout been mocked, but to call my `afterReveal` method, how I can?

**Comment by jlmakes** [comment] 2017-05-07 23:03
Ah okay, I think I know what's going on.

First, allow me to clarify how these callbacks work. This sounds a little weird, but it simply isn’t enough to call `reveal()` and expect `options.afterReveal` to fire...

There are 4 callbacks:
- `options.beforeReveal`
- `options.afterReveal`
- `options.beforeReset`
- `options.afterReset`

These callbacks fire at different **stages of animation**: before and after the reveal animation, and if you’re using `options.reset`, before and after the reset animations.

And this is what I believe the problem is. In order to trigger these animations (and subsequently the `options.afterReveal` callback), ScrollReveal has to be able to traverse the DOM to get the element’s total top and left offset, and compare that with current scroll distance and container size.

I personally use Karma _and real browsers_ to run my ScrollReveal tests, because the library is so deeply reliant on the DOM. It could be possible to use something like [JSDom](https://github.com/tmpvar/jsdom) to keep things in Node, but I unfortunately can't offer much help on that.

**Closed** 2017-05-16 02:39 UTC
Labels: Question, Third Party
